### ISSUE TITLE
[Feature Request] Update CFP related page content 

### ISSUE THREAD

**Issue by jordanSu** [pycontw/pycontw-frontend#188]
## Is your feature request related to a problem?
No

## Describe the solution you'd like
The CFP related page content could be updated to fit PyCon APAC 2022

## Describe alternatives you've considered
The program team should provide the page content, and we should update the code according to the content.

## Invite the community to discuss and vote

Earn votes and support by involving the community and invite everybody to discuss your feature and
to vote for it (votes are +1 , 0 or -1 via adding a **thumbs-up/down**)

**Comment by jordanSu** [comment]
Already solved in #193, I think we can close this issue?

**Comment by mattwang44** [comment]
Ok got it!
We can link the PR to corresponding issues in the future!
