### ISSUE TITLE
[Feature Request] Update Sprints page content on website

### ISSUE THREAD

**Issue by jordanSu** [pycontw/pycontw-frontend#191]
## Is your feature request related to a problem?
No

## Describe the solution you'd like
The updated Sprints information could be displayed on PyCon APAC 2022 website

## Describe alternatives you've considered

The program team should provide the page content, and we should update the code according to the content.

## Invite the community to discuss and vote

Earn votes and support by involving the community and invite everybody to discuss your feature and
to vote for it (votes are +1 , 0 or -1 via adding a **thumbs-up/down**)

**Comment by mattwang44** [comment]
I assume this issue is resolved by #192?

**Comment by jordanSu** [comment]
> I assume this issue is resolved by #192?

Yes I agree, let me close this issue.
