### ISSUE TITLE
[landing page]navigation bar style 需調整

### ISSUE THREAD

**Issue by anan0202** [pycontw/pycontw-frontend#198]
## Description
![image](https://user-images.githubusercontent.com/86242317/156284638-eea9565d-ccd2-4fc8-9e2c-fb9274fa9f9a.png)

1. navbar 高度應為56現在為48
2. navbar 字體應為19現在為17.5
3. dropdown 字體應為18現在為15
4. speaking 應改為proposal
5. background 背景顏色為 #1A1A30
![image](https://user-images.githubusercontent.com/86242317/156284698-638b5a03-0ee3-4c08-b8ee-c2880b4381bd.png)
6. call for proposal 按鈕應為實心（有填色）顏色為 ＃1A1A30
且圓角為40，for為小寫
字體為Noto Serif

## Expected Behavior
![image](https://user-images.githubusercontent.com/86242317/156285310-48bdd362-6c08-4e96-85fd-9fe8eb579884.png)
![image](https://user-images.githubusercontent.com/86242317/156285326-48693405-9281-4b51-84f5-87d9df5b3a75.png)

Figma工作區：https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=0%3A1

**Comment by mattwang44** [comment]
@anan0202 想請問 call for proposal 按鈕有 hovering style 嗎？我在 figma 上沒有找到，還是維持目前樣式就好？

**Comment by anan0202** [comment]
@mattwang44 
有的！
![image](https://user-images.githubusercontent.com/86242317/156307598-3986e89c-4bc4-4c66-a894-05e6f02676a2.png)
這裏這裡有！
可以的dropdown 可以加寬

**Comment by mattwang44** [comment]
@anan0202 

> 可以的dropdown 可以加寬我現在的版本是168如果不夠可以調整至176

想請問是以不斷行為目標嗎？設成 176px 還是會被斷，目前至少要 192px 才都不會被斷行，所以應該要設 192px 嗎？還是可以挑整哪些地方？

176px:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/24987826/159350458-11138c51-7f97-4989-988f-9cec4ba27bfc.png">

192px:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/24987826/159350382-cb3295c0-a086-4312-a894-b867194b27e3.png">

**Comment by mattwang44** [comment]
Designer's follow up:
1. navbar 以及按鈕顏色改為 121023
2. 希望按鈕樣式可以明顯一點，所以將 hover 以及 default 樣式調換
3. navbar 高度改為 52
4. 標題文字位置調低
