### ISSUE TITLE
[Feature Request] Update Events Overview page

### ISSUE THREAD

**Issue by jordanSu** [pycontw/pycontw-frontend#199]
## Is your feature request related to a problem?
No

## Describe the solution you'd like

Update the Events Overview page up to 2022 version.

## Describe alternatives you've considered

Program team will prepare the en-us/zh-hant contents to update, and update the code according to the prepared contents 

## Invite the community to discuss and vote

Earn votes and support by involving the community and invite everybody to discuss your feature and
to vote for it (votes are +1 , 0 or -1 via adding a **thumbs-up/down**)

**Comment by mattwang44** [comment]
reference:

- [figma](https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=3709%3A18908)
- [2021 version](https://tw.pycon.org/2021/zh-hant/events/overview)

<img width="377" alt="image" src="https://user-images.githubusercontent.com/24987826/180593283-f51d7820-ec1f-424a-8f14-4bf0442faf93.png">
