### ISSUE TITLE
[Feature Request] explicit "online/virtual/remote" message

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycontw-frontend#217]
## Describe the solution you'd like
The program and sponsorship team are aware that potential speakers and sponsors were asking if the conference will be hosted virtually or in-person.

## Describe alternatives you've considered
Put the information on the landing page explicitly.

## Additional context
The discord thread of the program team https://discord.com/channels/752904426057892052/752906124780634152/963400015173263420

**Comment by mattwang44** [comment]
Designers' update: we'll have a new section on the index page
<img width="576" alt="image" src="https://user-images.githubusercontent.com/24987826/165118409-466f60a4-2af9-414d-8546-0189247cac5a.png">
