### ISSUE TITLE
[Feature Request] Revamp core banner style

### ISSUE THREAD

**Issue by mattwang44** [pycontw/pycontw-frontend#230]
## Description

Revamp the banner style to conform to the design spec.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/24987826/165117535-28604e12-70e5-4919-a5b0-bf4d84b68bbc.png">

## Additional context

- [Figma](https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=1637%3A16898)
- Current style
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/24987826/165117400-899f6ec4-fa1d-425b-9b75-67d274536805.png">

**Comment by SivanYeh** [comment]
果不如期然來解鎖提問功能了：Banner的background image一般是如何產生的？

這邊想的到的方法是:
1. 使用素材庫按圖施工成svg
2. 找尋可以將png轉換成svg的方法
3. 跟設計師直接要svg

**Comment by SivanYeh** [comment]
New questions:
1. 如何調整title/abstract與Banner/大會資訊的間距?
—試過在mainstyle加入space-y-n(https://tailwindcss.com/docs/space)和mb-n(https://tailwindcss.com/docs/margin#add-margin-to-a-single-side). 不過版型並沒有變化. 
![image](https://user-images.githubusercontent.com/26858727/172431106-d34f160b-c688-4a03-8b2e-e8105d81fa63.png)

2. mt-16應用在vertstyle(先前的minpage)時似乎會出現過多的空間, 可能的原因是?
<img width="305" alt="image" src="https://user-images.githubusercontent.com/26858727/172431069-9db3ba2d-2962-4a69-b9c6-e2790c7f9a07.png">

**Comment by SivanYeh** [comment]
找到問題2的解答:
使用tailwindcss invisible時, invisible的區塊雖不會顯示圖形與內容, 但區塊會被保留.
如果想要避免區塊影響到其他內容, 需要多些設定 e.g h-0.
而Banner component與其他elements重疊, 主因是tailwindcss flex與css height 出現conflict. 可以參考這篇解釋:
https://stackoverflow.com/questions/64744897/how-to-not-overlap-components-using-tailwind-css

**Comment by mattwang44** [comment]
Close this PR as #266 is merged. 
Following issue is recorded in #267
