### ISSUE TITLE
[購票頁面 Banner style 調整] 

### ISSUE THREAD

**Issue by anan0202** [pycontw/pycontw-frontend#267]
## Description

<img width="367" alt="image" src="https://user-images.githubusercontent.com/86242317/176131577-d7b84060-4a46-4c65-a8da-5c3fac56a015.png">
1.Title『探索無疆宇宙...』web版本字體大小為40, rwd版本大小為32

2.rwd版本的『福爾摩斯號』這句需換行

3.『多樣票價』rwd 內文字體大小為17

4.『大會資訊』等Title顏色皆為E099E1

5.Banner 、大會資訊、購票方案間距過寬(rwd及web版本皆是）

預期效果
<img width="278" alt="image" src="https://user-images.githubusercontent.com/86242317/176134506-9bad2c3e-7638-4dda-a1d7-47cf38b1843c.png">

**Comment by josix** [comment]
Close this as completed in #286
