### ISSUE TITLE
[衝刺開發頁面] Style調整

### ISSUE THREAD

**Issue by anan0202** [pycontw/pycontw-frontend#282]
## Description

![image](https://user-images.githubusercontent.com/86242317/179143680-b77583f3-36b4-4466-a8b3-9b6b3271b583.png)
目前衝刺開發頁面設計未符合設計 Style
（衝刺開發頁面當初因為比較急著發佈因此沒有看設計稿就開發）

![image](https://user-images.githubusercontent.com/86242317/179143955-8400cc2e-7fa3-4b9c-9915-8081eb0f0883.png)

Figma：https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=4266%3A27625

**Comment by mattwang44** [comment]
https://github.com/pycontw/pycontw-frontend/blob/main/components/core/layout/TwoColWrapper.vue
https://tw.pycon.org/2022/en-us/registration/financial-aid

**Comment by josix** [comment]
Close this as completed in #320
