### ISSUE TITLE
[首頁] Rwd Style 調整

### ISSUE THREAD

**Issue by anan0202** [pycontw/pycontw-frontend#283]
## Description

![image](https://user-images.githubusercontent.com/86242317/179148552-5d8461cd-9cfc-410b-a9be-e7de9e3230e1.png)
1.首頁 Rwd 背景圖片未置中（或者說沒有置換為 Rwd 圖片)
2.Rwd的『PyCon APAC Taiwan September...』等標題字體需調大
3.Rwd以及網頁版的『立即購票』的按鈕應在『何謂PyCon』標題之上
4.Rwd 的『何謂 PyCon』、『PyCon APAC將會線上舉辦』等標題需置中
以下為設計稿示意圖
![image](https://user-images.githubusercontent.com/86242317/179148677-60a1f952-e566-4327-b345-ee366f443257.png)

5.Rwd 的『PyCon Taiwan』標題與『持續舉辦...』的間距需增加
6.Rwd 『持續舉辦』與『10』與『年』之間的間距需增加（其他以此類推）
目前的畫面：
![image](https://user-images.githubusercontent.com/86242317/179150204-318a3c7d-66b0-48eb-87aa-a35b5fe658c2.png)

以下為設計稿示意圖
![image](https://user-images.githubusercontent.com/86242317/179150034-1377e896-e3cd-49d6-84dc-b49af737d121.png)

Figma連結：https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=31%3A1821

**Comment by josix** [comment]
Solved by #317
