### ISSUE TITLE
[Young Inspirers Page] Unformatted description for young inspirers speaker 陳怡升

### ISSUE THREAD

**Issue by jordanSu** [pycontw/pycontw-frontend#284]
## Description
~~The description of 陳怡升 should be~~
```
怡升 Eason：（名字含義）怡然自得的提升自己，帶著快樂的心成長向上
現在：
    1. 學習科學大四 
    2. 研究助理 
    3. 區塊鏈新創 Cohart 研發工程師 
    4. 認真的基督徒
過去：
    1. 網路成癮：一天玩八小時
    2. 成績墊底：高中校排常駐最後一名
    3. 內向害羞、不善溝通交際
未來夢想：
    1. 出國讀研究所、見識世界
    2. 創業

更多關於我，請參考：前年在大直國中分享投影片
內容：
    1. 我的故事
    2. 亞斯伯格的特質
    4. 如何學習？
https://www.facebook.com/media/set/?set=a.3040151202767474&type=3

```
~~But it's currently unformatted.~~

### Updated
怡升有給我們最新的`議程簡介` 與 `講者介紹`如下
#### 議程簡介
陳怡升（EasonC13）現在大四，不僅在學校成績名列前茅，積極做研究並已發表過七篇論文，也有兩年產業經驗，現在國外新創 Cohart 擔任研發工程師。但怡升以前並不是如此，他高中時網路成癮，一天玩電腦八小時以上，在校成績也是全校倒數第一，更非常內向害羞不善交際。

在此訪談中我們將聽怡升分享他是如何克服生命的低谷，在大學找到自己的一片天。以及在這過程中領悟的「關鍵駭客思維」，究竟如何幫助他翻轉生命，持續成長向上。

#### 講者介紹
嗨，我是怡升！我的名字含義是「怡」然自得的提「升」自己，期許自己能帶著快樂的心持續成長向上。

我現在就讀臺師大學習科學學士班大四，同時在國外新創 Cohart 擔任研發工程師。因為之前討厭學習並網路成癮的經驗，我現在對如何幫助人更好的學習有很深的興趣，並積極投入教育、AI、人機互動與區塊鏈的研究。除此之外，我熱愛使用程式解決生活的問題，至今已開發過許多有趣的小應用，大部分都是用 Python 寫的。

對於這個活動，我希望分享我的生命故事，與從中體會到的重要價值，期待聽完這場分享的你，能像我一樣持續成長向上，活出更好的自己！

更多關於我，請見我的個人網站 https://eason.best/ 。

P.S. 我在今年（2022）的 PyCon APAC 將分享一場專業課程（Tutorial）：「90 分鐘帶你用 Brownie 上架 NFT」，如果你對「如何用 Python 操作區塊鏈智能合約並發行自己的 NFT 」有興趣，請一定要來聽喔！

## Steps to Reproduce

1. Go to https://tw.pycon.org/2022/en-us/conference/young-inspirers
2. Click on "陳怡升" to see speaker's bio

## Expected Behavior

The description should be formatted as like above mentioned.
Refer to [Original bio gdoc](https://docs.google.com/document/d/1UA749ycQM1Jen2-D2cWZIjl03tl3e5PtQNiTxhhxUv0/edit?usp=sharing)

## Actual Behavior

**Screenshots**
![Screen Shot 2022-07-16 at 11 34 56](https://user-images.githubusercontent.com/7271547/179335807-ae8ffbbc-da8b-47a4-80b8-396009ca427d.png)

**Comment by jordanSu** [comment]
Hello @mattwang44 @josix 
講者有給我們新版的內容，這個 issue 讓我來發 PR 更新好了

**Comment by josix** [comment]
放內容的架構有些改變我也同步更新在新的 PR

**Comment by jordanSu** [comment]
感恩讚嘆 @josix 大大幫忙

**Comment by mattwang44** [comment]
@jordanSu 可以麻煩你檢查一下目前版本合不合用嗎？
https://tw.pycon.org/2022/zh-hant/conference/young-inspirers

**Comment by mattwang44** [comment]
the new content has been released.
