### ISSUE TITLE
[Feature Request] Add particular thanks in home page Sponsors block

### ISSUE THREAD

**Issue by tyuchx** [pycontw/pycontw-frontend#324]
## Describe the solution you'd like

![CleanShot 2022-08-21 at 14 28 56@2x](https://user-images.githubusercontent.com/6921552/185778617-ec65d4da-7b66-4c73-855d-09c8bd15d455.png)

需要在 特別贊助 及 主辦單位 中間增加 特別感謝 區塊

### Logo
https://drive.google.com/drive/folders/1kCQzfEJ663jzGSHg559u373c61jlqnp3

### 介紹文以及連結
https://docs.google.com/spreadsheets/d/10pEr8cRehcQwmDQK-aOMirltSSC0FSYd9wv-gPhHmWM/edit#gid=0

**Comment by mattwang44** [comment]
will be resolved by #327 and https://github.com/pycontw/pycon.tw/pull/1097
