### ISSUE TITLE
[Schedule] Timeline 時間錯誤

### ISSUE THREAD

**Issue by tyuchx** [pycontw/pycontw-frontend#326]
## Description

![CleanShot 2022-08-21 at 15 08 48@2x](https://user-images.githubusercontent.com/6921552/185779884-a312c3ec-e882-4cc6-9f1f-e393e607449a.png)

議程時間變將 UTC 時間，且左側 Timeline 時間變成 UTC-8

**Comment by mattwang44** [comment]
Duplicate #305
