### ISSUE TITLE
Button Color, NavBar Hover Text Hover Color Changed to #DA8BDC

### ISSUE THREAD

**Issue by anan0202** [pycontw/pycontw-frontend#344]
## Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/86242317/203606515-0656fb6e-6ee4-416a-b6aa-7d69a3e48cae.png)

Button: BE3692 / 5B69E2 / 68B7E2 / 8BE1C2
NavBar 粉紅顏色更新: F38DFC

**Comment by josix** [comment]
@yungshenglu 這題也可以和首頁一起交給你嗎
