### ISSUE TITLE
[WebCache Error] : 404 Error Page on 2021 website

### ISSUE THREAD

**Issue by baby230211** [pycontw/pycontw-frontend#386]
## Description
As the user visit 2021 website on webcache page 
Then it will show 404 error page.

## Steps to Reproduce

open in google link site:https://tw.pycon.org/
choose in search result "頁庫存擋"
you open page https://webcache.googleusercontent.com/search?q=cache:9er0RXJ1v60J:https://tw.pycon.org/&cd=1&hl=zh-TW&ct=clnk&gl=tw&cd=1&hl=ru&ct=clnk&gl=ua
then page will redirect to https://tw.pycon.org/2023/en-us/search?q=cache%3A9er0RXJ1v60J%3Ahttps%3A%2F%2Ftw.pycon.org%2F&cd=1&hl=zh-TW&ct=clnk&gl=tw

## Expected Behavior

show correctly on webcache page

**Comment by josix** [comment]
sovled by #402
