### ISSUE TITLE
Archive PyCon TW 2023 Page

### ISSUE THREAD

**Issue by rockleona** [pycontw/pycontw-frontend#458]
Hi guys,
@josix had taught me that PyCon TW 2023 need to be archive as static pages,
I'll take this part and following the [instruction](https://github.com/pycontw/pycontw-frontend#archiving-the-historical-pycon-tw-website) from README to finish the task.

**Comment by rockleona** [comment]
Finish setup, will upload the archive content later, see #459

**Comment by rockleona** [comment]
Finding this error, seems like it's an common error which occurs when using leaflet in vue(nuxt).
l'll find some available time to fix it. 

<img width="998" alt="image" src="https://github.com/pycontw/pycontw-frontend/assets/34214497/e4e4b068-4dad-4ff0-8b94-86a42b5cf2b9">

**Comment by SivanYeh** [comment]
> > Thanks @rockleona! BTW, could you help follow the [instruction](https://github.com/pycontw/pycon_archive_past_website) to archive the 2023 site and upload it to [pycon_archive_past_website](https://github.com/pycontw/pycon_archive_past_website).
> 
> Finish setup, will upload the archive content later, see #459

I can't find 2024 repo [here](https://github.com/pycontw/pycon_archive_past_website) still. How's it going so far, need a hand? @josix cc @rockleona

**Comment by rockleona** [comment]
> > > Thanks @rockleona! BTW, could you help follow the [instruction](https://github.com/pycontw/pycon_archive_past_website) to archive the 2023 site and upload it to [pycon_archive_past_website](https://github.com/pycontw/pycon_archive_past_website).
> > 
> > 
> > Finish setup, will upload the archive content later, see #459
> 
> I can't find 2024 repo [here](https://github.com/pycontw/pycon_archive_past_website) still. How's it going so far, need a hand? @josix cc @rockleona

Still working on it, will update it today.
