### ISSUE TITLE
[Bug Report] Vue error from 'div' on page speaking/cfp

### ISSUE THREAD

**Issue by SivanYeh** [pycontw/pycontw-frontend#491]
## Description

**Describe the bug**
The following warning msg showed up while page speaking/cfp loading:
![image](https://github.com/pycontw/pycontw-frontend/assets/26858727/a9762b6e-acf6-4059-b9b2-5ca3dcae72a0)

## Steps to Reproduce

1. Go to 'http://localhost:3000/2024/zh-hant/speaking/cfp'
2. See error as the attached img in description

## Additional context
Related PR:
#469

**Comment by baby230211** [comment]
https://github.com/pycontw/pycontw-frontend/pull/492#issuecomment-1956785759
